-- Quant 系统初始化 SQL
-- 创建扩展
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "btree_gin";
CREATE EXTENSION IF NOT EXISTS "btree_gist";

-- 创建 Schema
CREATE SCHEMA IF NOT EXISTS quant;
CREATE SCHEMA IF NOT EXISTS dagster;
CREATE SCHEMA IF NOT EXISTS tenant;
CREATE SCHEMA IF NOT EXISTS audit;

-- 设置搜索路径
ALTER DATABASE quant SET search_path TO quant, dagster, tenant, audit, public;

-- 权限
GRANT ALL PRIVILEGES ON DATABASE quant TO quant;
GRANT ALL ON SCHEMA quant TO quant;
GRANT ALL ON SCHEMA dagster TO quant;
GRANT ALL ON SCHEMA tenant TO quant;
GRANT ALL ON SCHEMA audit TO quant;

-- 默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA quant GRANT ALL ON TABLES TO quant;
ALTER DEFAULT PRIVILEGES IN SCHEMA dagster GRANT ALL ON TABLES TO quant;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant GRANT ALL ON TABLES TO quant;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT ALL ON TABLES TO quant;
